# Generated by Django 5.2.7 on 2025-10-19 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=200)),
                ('id_passport', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('ethnicity', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField()),
                ('special_interest', models.JSONField(blank=True, default=list)),
                ('pwd_number', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('polling_station', models.CharField(blank=True, max_length=200)),
                ('membership_category', models.CharField(choices=[('Ordinary Membership', 'Ordinary Membership'), ('Bronze Membership', 'Bronze Membership'), ('Life Membership', 'Life Membership'), ('Associate Membership', 'Associate Membership'), ('Group Membership', 'Group Membership'), ('Honorary Membership', 'Honorary Membership')], max_length=50)),
                ('membership_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('certificate_generated', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_sent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['membership_number'], name='membership__members_90d50f_idx'), models.Index(fields=['id_passport'], name='membership__id_pass_82ee73_idx'), models.Index(fields=['email'], name='membership__email_f208cc_idx')],
            },
        ),
    ]
